# Generated by Django 4.2.7 on 2023-11-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='route_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
