# Generated by Django 4.2.7 on 2023-11-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
        ('document', '0004_document_created_document_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='released_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='route_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
