# Generated by Django 4.2.7 on 2023-11-30 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0005_document_approved_by_document_released_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tracking',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_trackings', to=settings.AUTH_USER_MODEL),
        ),
    ]
