# Generated by Django 4.2.7 on 2023-12-01 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('document', '0006_document_accepted_by_tracking_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_document', to='login.department'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_trackings', to='login.department'),
        ),
    ]
