# Generated by Django 4.2.7 on 2023-12-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('document', '0007_alter_document_accepted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cycle_end_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_end_document', to='login.department'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='cycle_end_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_end_tracking', to='login.department'),
        ),
    ]
