# Generated by Django 4.2.7 on 2023-12-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('document', '0008_document_cycle_end_by_tracking_cycle_end_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='returned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_tracking', to='login.department'),
        ),
    ]
