# Generated by Django 4.2.7 on 2023-12-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('document', '0009_tracking_returned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='returned_by',
            new_name='returned_to',
        ),
        migrations.AddField(
            model_name='document',
            name='returned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_document', to='login.department'),
        ),
    ]
